### PR TITLE
Add visual studio code format on save hook

### PR DESCRIPTION
**Pull request by skylerrichter**
**What I Did:**

- Added format on save hook for Visual Studio Code.

### CODE REVIEW

**Review by davidvandusen — COMMENTED** [review]
This change brings a few questions to mind.

Is every VS Code user going to prefer this workflow, or are some users going to prefer a different configuration?

Does this invite VS Code users to contribute more contentious rules to the project, which if added would disrupt devs' abilities to configure their workflows as they please?

Is there some way of creating a configuration that works for everyone, including non-VS Code users?

Isn't it conventional for devs to add files that their tools create to their [global gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) file? Will the existence of this file be confusing for devs who are following that best practice and including their personal config into this file? Instead of committing this, would a better change be to add some of the common IDE config files to this project's gitignore?

**Comment by skylerrichter** [comment]
The rational for adding on save hooks for prettier was just past experience, and your questions raise some valid points.

At my previous job I was working with a lot of university co-ops and junior developers so the reason for using on save hooks over something like husky pre-commit hooks was:

- 99% of the developers I worked with at that level, their go-to code editor was VSCode.
- Expecting a developer at that level to configure their editor to work as expected was hit or miss and having the .vscode file committed directly to the repo simplified the whole onboarding process.
- Husky + prettier/eslint can be finicky. A recurring issue I had with more junior devs was line endings on different operating systems (usually windows users not being able to commit since their editor changed a bunch of line endings).

That being said we probably don't have a lot of juniors around here and having something like husky commit hooks would be more reliable than hoping everyone uses VSCode.

Ultimately you're right, not all developers will use VSCode, and out of the ones that do this may not be the preferred setup.

I can squash these PRs and setup Husky if that would be preferable.

**Comment by davidvandusen** [comment]
I'm curious what the best Husky setup would be, if we decided to go that route. The old TESSA repo had Husky doing checks on pre-commit, and it started to annoy the heck out of me that I had to wait for the checks before my commit would succeed.

It's a bit of a conundrum—I'll likely be annoyed by any pre-commit hook and start skipping checks when committing. If the pre-commit hooks weren't there, someone else would likely be annoyed by the CI telling them their files need to be formatted and de-linted before they can merge.

If Husky was added and checks configured, is it possible to make them opt-in?

**Comment by skylerrichter** [comment]
I believe you can use the no verify flag e.g. `git commit -m "message" --no-verify`.

**Comment by davidvandusen** [comment]
Yeah, that's what I started doing out of frustration with Husky. It's a bad habit, though. I would rather not have to commit with `--no-verify` and just opt-into the checks that work for me.

**Pull request closed without merging**
